exports.testStartData = {
	archie: ['a', 'b', 'c'],
	billy: ['a', 'b', 'c'],
	camilla: ['d', 'e', 'f'],
	debbie: ['d', 'e', 'f'],
	Eddie: ['a', 'b', 'c'],
	Frannie: ['a', 'b', 'c']	
};

exports.testEndData = {
	archie: ['a', 'd', 'e'],
	billy: ['b', 'e', 'f'],
	camilla: ['d', 'a', 'b'],
	debbie: ['e', 'b', 'c'],
	Eddie: ['d'],
	Frannie: ['d']
};


exports.currentClientAndMarketers = {
	Hugo_Boss : ['Jay',	'Jake',	'Katie', 'Sabrina',	'Greg'],
	Hopsy : ['Jenna',	'Kaveh',	'Eduardo'],
	Hurley : ['Amanda'],
	Spanx : ['Jenna',	'Nick',	'Kyra',	'Megan_Burke'],
	Alice_Olivia : ['Michael',	'Tianna',	'Langston'],
	FragranceX : ['Jay',	'Marco',	'Sabrina'],
	Bonafide : ['Katie',	'Megan_Blissick',	'Mathias'],
	Draper_James : ['Jenna',	'Kyra',	'Charmaine'],
	Glamsquad : ['Langston',	'Neyha'],
	Vroom : ['Jay',	'Marco',	'Ritikaa'],
	Hook_Albert : ['Greg',	'Mathias',	'Ritikaa'],
	Shake_Shack : ['Greg',	'Jake',	'Sabrina'],
	TeePublic : ['Jenna',	'Nick',	'Eduardo',	'Charmaine'],
	Extend_Fertility : ['Greg',	'Mathias',	'Ritikaa'],
	Jack_Rogers : ['Nick', 'Kyra'],
	Koio_Collective : ['Greg',	'Mathias',	'Jake'],
	Twillory : ['Greg',	'Jake',	'Ritikaa'],
	Stone_Strand : ['Jenna',	'Megan_Burke'],
	Spartina : ['Kaveh',	'Charmaine'],
	Bandier : ['Asher',	'Casey',	'Weiru'],
	Clear : ['Anthony',	'Gio',	'Richard',	'Jamie',	'Leo'],
	Nutraceutical_Wellness : ['Tyler',	'Hoon',	'Chris',	'Hannah',	'Anthony_M',	'Weiru'],
	Trade_Coffee : ['Tyler',	'Chris',	'Anthony_M',	'Weiru'],
	Blue_Bottle_Coffee : ['Michael',	'Neyha',	'Min'],
	Diesel : ['Tyler',	'Biz',	'Weiru'],
	Food52 : ['Areeb',	'Danielle'],
	CollectedGroup : ['Gio',	'Stephanie',	'Leo'],
	Lo_Sons : ['Areeb',	'Neyha',	'Mary'],
	PetFlow : ['Tyler',	'Casey',	'Anthony_M',	'Weiru'],
	Spartan_Race : ['Areeb',	'Danielle',	'Mary',	'Min',	'Tianna',	'Langston'],
	WellPet : ['Areeb',	'Mary',	'Tianna'],
	One_Drop : ['Hoon',	'Biz',	'Weiru'],
	Greats : ['Anthony',	'Gio',	'Richard',	'Stephanie'],
	Margaux : ['Anthony',	'Jamie',	'Stephanie'],
	Master_Dynamic : ['Jamie',	'Gio',	'Stephanie'],
	Scotch_Soda : ['Danielle',	'Min'],
	Ever_After : ['Michael',	'Mary',	'Neyha'],
	Hubble : ['Michael',	'Areeb',	'Danielle'],
	Shine : ['Richard',	'Jamie'],
	Assos : ['Anthony',	'Leo',	'Jamie'],
	Sonnet_James : ['Danielle',	'Min'],
	Ash_Erie : ['Hoon',	'Casey',	'Anthony_M'],
	Zachary_Prell : ['Austin',	'Sabrina']
}


exports.projectedClientAndMarketers = {
	Hugo_Boss	: ['Jay', 'Greg', 'Katie', 'Jake'],
	Hopsy : ['Kaveh', 'Ritikaa', 'Jenna'],
	Hurley : ['Amanda', 'Megan_Burke'],
	Spanx	: ['Jenna', 'Nick', 'Kyra', 'Megan_Burke'],
	Alice_Olivia : ['Langston', 'Tianna', 'Charmaine'],
	FragranceX	: ['Marco', 'Tianna'],
	Bonafide : ['Amanda', 'Katie', 'Kyra'],
	Draper_James : ['Jenna', 'Kyra', 'Charmaine'],
	Glamsquad	: ['Langston', 'Katie', 'Nick_R'],
	Vroom : ['Marco', 'Ritikaa'],
	Hook_Albert	: ['Greg', 'Mathias'],
	Shake_Shack : ['Greg', 'Jake'],
	TeePublic	: ['Nick', 'Charmaine', 'Tianna'],
	Extend_Fertility : ['Amanda', 'Mathias'],
	Jack_Rogers : ['Nick', 'Kyra'],
	Koio_Collective	: ['Langston', 'Mathias'],
	Twillory : ['Greg', 'Jake'],
	Stone_Strand : ['Kaveh', 'Megan_Burke'],
	Spartina	: ['Kaveh', 'Charmaine'],
	Bandier : ['Nick', 'Ritikaa', 'Mathias'],
	Clear	: ['Gio', 'Jamie'],
	Nutraceutical_Wellness : ['Hoon', 'Chris', 'Hannah', 'Anthony_M', 'Weiru'],
	Trade_Coffee	: ['Tyler', 'Anthony_M', 'Chris', 'Weiru'],
	Blue_Bottle_Coffee	: ['Devon', 'Hannah'],
	Diesel : ['Hoon', 'Biz', 'Weiru'],
	Food52 : ['Areeb'],
	CollectedGroup : ['Gio'],
	Lo_Sons : ['Areeb'],
	PetFlow : ['Tyler', 'Anthony_M'],
	Spartan_Race : ['Areeb'],
	WellPet	: ['Areeb'],
	One_Drop	: ['Hoon', 'Biz', 'Weiru'],
	Greats	: ['Gio'],
	Margaux : ['Jamie'],
	Master_Dynamic	: ['Jamie'],
	Scotch_Soda	: ['Danielle'],
	Ever_After	: ['Danielle'],
	Hubble	: ['Chris'],
	Shine	: ['Jamie', 'Hannah'],
	Assos	: ['Devon', 'Leo'],
	Sonnet_James	: ['Danielle'],
	Ash_Erie : ['Hoon', 'Anthony_M']
}




