exports.testStartData = {
	archie: ['a', 'b', 'c'],
	billy: ['a', 'b', 'c'],
	camilla: ['d', 'e', 'f'],
	debbie: ['d', 'e', 'f'],
	Eddie: ['a', 'b', 'c'],
	Frannie: ['a', 'b', 'c']	
};

exports.testEndData = {
	archie: ['a', 'd', 'e'],
	billy: ['b', 'e', 'f'],
	camilla: ['d', 'a', 'b'],
	debbie: ['e', 'b', 'c'],
	Eddie: ['d'],
	Frannie: ['d']
};


exports.currentClientAndMarketers = {
	Hugo_Boss : ['Jay',	'Jake',	'Katie', 'Sabrina',	'Greg'],
	Hopsy : ['Jenna',	'Kaveh',	'Eduardo'],
	Hurley : ['Amanda'],
	Spanx : ['Jenna',	'Nick',	'Kyra',	'Megan_Burke'],
	Alice_Olivia : ['Michael',	'Tianna',	'Langston'],
	FragranceX : ['Jay',	'Marco',	'Sabrina'],
	Bonafide : ['Katie',	'Megan_Blissick',	'Mathias'],
	Draper_James : ['Jenna',	'Kyra',	'Charmaine'],
	Glamsquad : ['Langston',	'Kyra',	'Tianna'],
	Vroom : ['Jay',	'Marco',	'Ritikaa'],
	Hook_Albert : ['Greg',	'Mathias',	'Ritikaa'],
	Shake_Shack : ['Greg',	'Jake',	'Sabrina'],
	TeePublic : ['Jenna',	'Nick',	'Eduardo',	'Charmaine'],
	Extend_Fertility : ['Greg',	'Mathias',	'Ritikaa'],
	Jack_Rogers : ['Nick', 'Kyra'],
	Koio_Collective : ['Greg',	'Mathias',	'Jake'],
	Twillory : ['Greg',	'Jake',	'Ritikaa'],
	Stone_Strand : ['Jenna',	'Megan_Burke'],
	Spartina : ['Kaveh',	'Charmaine'],
	Bandier : ['Asher',	'Casey',	'Weiru'],
	Clear : ['Anthony_J',	'Gio',	'Richard',	'Jamie',	'Leo'],
	Nutraceutical_Wellness : ['Tyler',	'Hoon',	'Chris',	'Hannah',	'Anthony_M',	'Weiru'],
	Trade_Coffee : ['Tyler',	'Chris',	'Anthony_M',	'Weiru'],
	Blue_Bottle_Coffee : ['Michael',	'Neyha',	'Min'],
	Diesel : ['Tyler',	'Biz',	'Weiru'],
	Food52 : ['Areeb',	'Danielle'],
	CollectedGroup : ['Gio',	'Stephanie',	'Leo'],
	Lo_Sons : ['Areeb',	'Neyha',	'Mary'],
	PetFlow : ['Tyler',	'Casey',	'Anthony_M',	'Weiru'],
	Spartan_Race : ['Areeb',	'Danielle',	'Mary',	'Min',	'Tianna',	'Langston'],
	WellPet : ['Areeb',	'Mary',	'Tianna'],
	One_Drop : ['Hoon',	'Biz',	'Weiru'],
	Greats : ['Anthony_J',	'Gio',	'Richard',	'Stephanie'],
	Margaux : ['Anthony_J',	'Jamie',	'Stephanie'],
	Master_Dynamic : ['Jamie',	'Gio',	'Stephanie'],
	Scotch_Soda : ['Danielle',	'Min'],
	Ever_After : ['Michael',	'Mary',	'Neyha'],
	Hubble : ['Michael',	'Areeb',	'Danielle'],
	Shine : ['Richard',	'Jamie'],
	Assos : ['Anthony_J',	'Leo',	'Jamie'],
	Sonnet_James : ['Danielle',	'Min'],
	Ash_Erie : ['Hoon',	'Casey',	'Anthony_M'],
	Zachary_Prell : ['Austin',	'Sabrina']
}


exports.projectedClientAndMarketers = {
	Hugo_Boss	: ['Jay', 'Tianna', 'Katie', 'Jake'],
	Hopsy : ['Kaveh', 'Ritikaa', 'Jenna', 'Devon'],
	Hurley : ['Amanda', 'Megan_Burke'],
	Spanx	: ['Jenna', 'Nick', 'Kyra', 'Megan_Burke'],
	Alice_Olivia : ['Langston', 'Tianna', 'Mathias'],
	FragranceX	: ['Marco', 'Tianna', 'Devon'],
	Bonafide : ['Greg',	'Katie',	'Mathias'],
	Draper_James : ['Jenna', 'Charmaine'],
	Glamsquad	: ['Langston', 'Katie', 'Nick_R'],
	Vroom : ['Marco', 'Ritikaa'],
	Hook_Albert	: ['Greg', 'Ritikaa', 'Mathias'],
	Shake_Shack : ['Greg', 'Jake', 'Charmaine'],
	TeePublic	: ['Nick', 'Charmaine', 'Devon'],
	Extend_Fertility : ['Greg',	'Mathias',	'Ritikaa'],
	Jack_Rogers : ['Nick', 'Kyra', 'Devon'],
	Koio_Collective	: ['Greg',	'Mathias', 'Ritikaa'],
	Twillory : ['Greg', 'Jake', 'Ritikaa'],
	Stone_Strand : ['Jenna',	'Megan_Burke'],
	Spartina	: ['Kaveh', 'Charmaine'],
	Bandier : ['Asher'],
	Clear	: ['Gio',	'Biz',	'Leo',	'Sabrina'],
	Nutraceutical_Wellness : ['Tyler', 'Hoon', 'Chris', 'Hannah', 'Weiru'],
	Trade_Coffee	: ['Tyler', 'Anthony_M', 'Devon'],
	Blue_Bottle_Coffee	: ['Langston',	'Megan_Burke'],
	Diesel : ['Hoon', 'Biz', 'Weiru'],
	Food52 : ['Areeb', 'Danielle'],
	CollectedGroup : ['Gio'],
	Lo_Sons : ['Areeb',	'Mary',	'Nick_R'],
	PetFlow : ['Gio',	'Danielle',	'Nick_R',	'Anthony_M'],
	Spartan_Race : ['Areeb',	'Danielle',	'Mary',	'Nick_R'],
	WellPet	: ['Areeb',	'Mary',	'Sabrina',	'Chris'],
	One_Drop	: ['Hoon', 'Biz'],
	Greats	: ['Anthony_J',	'Gio',	'Devon',	'Nick_R'],
	Margaux : ['Jamie', 'Katie', 'Megan_Burke'],
	Master_Dynamic	: ['Jamie',	'Gio',	'Kyra'],
	Scotch_Soda	: ['Danielle', 'Weiru'],
	Ever_After	: ['Gio',	'Mary',	'Anthony_M'],
	Hubble	: ['Areeb',	'Devon',	'Danielle'],
	Shine	: ['Jamie',	'Greg',	'Marco'],
	Assos	: ['Hoon',	'Leo',	'Hannah'],
	Sonnet_James	: ['Danielle', 'Nick_R'],
	Ash_Erie : ['Hoon', 'Anthony_M', 'Leo'],
	TCG: ['Gio',	'Leo',	'Hannah'],
	Fig_Loans: ['Areeb',	'Chris',	'Sabrina'],
	Choosy: ['Hoon',	'Sabrina',	'Weiru'],
	Gravity_Blankets: ['Areeb',	'Mary'],
	Hickory_Farms: ['Nick',	'Kaveh'],
	Legends: ['Mathias']
}




